"""add_user_id_to_problem

Revision ID: ccd97e7457f5
Revises: cda24d6f66d4
Create Date: 2026-04-16 18:12:20.251164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccd97e7457f5'
down_revision: Union[str, None] = 'cda24d6f66d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('user_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'user_id')
    # ### end Alembic commands ###
